# Generated by Django 2.2.4 on 2020-01-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('inputfile_path', models.CharField(max_length=50)),
                ('profile_path', models.CharField(max_length=50)),
                ('prediction', models.CharField(max_length=30)),
            ],
        ),
    ]
