# Generated by Django 2.2.4 on 2020-01-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='profile_path',
            new_name='processedfile_path',
        ),
    ]
