# Generated by Django 2.2.4 on 2020-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200115_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='prediction',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='data',
            name='processedfile_path',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
