# Generated by Django 2.2.4 on 2020-01-15 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_launchpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchpad',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
