# Generated by Django 2.2.4 on 2020-01-16 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_launchpad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
