# Generated by Django 3.0.2 on 2020-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='altitude',
            field=models.FloatField(blank=True),
        ),
    ]
