# Generated by Django 3.0.2 on 2020-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200116_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='altitude',
            field=models.FloatField(default=0, null=True),
        ),
    ]
