# Generated by Django 3.0.2 on 2020-01-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200116_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchpad',
            name='missile',
            field=models.CharField(default='BrahMos', max_length=30),
        ),
    ]
