# Generated by Django 3.0.2 on 2020-01-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200116_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='missile',
            field=models.CharField(default='No missile', max_length=30),
        ),
    ]
