# Generated by Django 3.0.2 on 2020-01-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200116_1901'),
        ('app', '0008_auto_20200117_0103'),
    ]

    operations = [
    ]
